piVersion: apps/v1
kind: Deployment
metadata:
  name: paymybuddy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymybuddy-backend
  template:
    metadata:
      labels:
        app: paymybuddy-backend
    spec:
      containers:
      - name: paymybuddy-backend
        image: titan111/paymybuddy-backend:latest
        ports:
          - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-pvc
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pvc
              key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: connection-url
